---
title: "Hard Work 12"
author: "Dylan McDowell"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
    code_folding: hide
---

<style>

</style>

## Instructions

1. Study Sections **12.1, 12.2, 12.3, 12.4, 12.5** -- "**The sections are about time series analysis and the problems that often arise due to things like autocorrelation.**."

2. Attempt and submit at least <span id=points style="padding-left:0px;">{50}</span> Hard Work Points by Saturday at 11:59 PM.    
<span id=note>Over <span id=points style="padding-left:0px;">{65}</span> gets you {+1} Final Exam Point.</span>    
<span id=note>Over <span id=points style="padding-left:0px;">{80}</span> gets you {+2} Final Exam Points.</span>    


## Reading Points <span id=headpoints>{24} Possible</span>

### Section 12.1 <span id=rrecpoints>{2}</span><span id=report>{  /  }</span>

### Section 12.2 <span id=rrecpoints>{6}</span><span id=report>{  /  }</span>

### Section 12.3 <span id=rrecpoints>{2}</span><span id=report>{  /  }</span>

### Section 12.4 <span id=rrecpoints>{12}</span><span id=report>{  /  }</span>

### Section 12.5 <span id=rrecpoints>{4}</span><span id=report>{  /  }</span>

## Theory Points <span id=headpoints>{10} Possible</span>

### Problem 12.1 <span id=points>{2}</span><span id=report>{ / }</span>

### Problem 12.2 <span id=points>{2}</span><span id=report>{ / }</span>

### Problem 12.3 <span id=recpoints>{2}</span><span id=report>{ / }</span>

### Problem 12.4 <span id=recpoints>{4}</span><span id=report>{ / }</span>

## Application Points <span id=headpoints>{31} Possible</span>

<a id=datalink style="font-size:.9em;" target="_blank" href=http://www.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/textdatasets/index.html>Data Files</a>

### Problem 12.10 <span id=recpoints>{9}</span><span id=report>{ / }</span>

```{r}
# Here is generic code that would read in any "Problem" from any "Chapter":

Chapter <- 11 #change this to the chapter you want
Problem <- 11 #change this to the problem you want

#Change pWhatever.Whatever to be p11.11 or whatever you want.
pWhatever.Whatever <- read.table(paste0("http://www.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/textdatasets/KutnerData/Chapter%20", Chapter, "%20Data%20Sets/CH", Chapter, "PR", Problem, ".txt"), header=FALSE)

# Give it nice column names for conevience:
# Be sure to change pWhatever.Whatever to p11.11 or whatever you used above.
colnames(pWhatever.Whatever) <- c("Y","X1")

```

### Problem 12.13 <span id=recpoints>{6}</span><span id=report>{ / }</span>

### Problem 12.10 <span id=recpoints>{9}</span><span id=report>{ / }</span>

### Problem 12.17 <span id=recpoints>{7}</span><span id=report>{ / }</span>

### Problem 12.18 <span id=points>{9}</span><span id=report>{ / }</span>

## Projects <span id=headpoints>{8} Possible</span>

### Project 12.27 <span id=points>{8}</span><span id=report>{ / }</span>

## Case Studies <span id=headpoints>{12} Possible</span>

### Project 12.29 <span id=points>{12}</span><span id=report>{ / }</span>

<footer>
</footer>



 
<style>
 #points {
  font-size:.8em;
  padding-left:5px;
  font-weight:bold; 
  color:#317eac;
}

#recpoints {
  font-size:.8em;
  padding-left:5px;
  font-weight:bold; 
  color:#7eac31;
}

#rrecpoints {
  font-size:1em;
  padding-left:5px;
  font-weight:bold; 
  color:#7eac31;
}

#report {
  font-size:.7em;
  padding-left:15px;
  font-weight:normal; 
  color:#5a5a5a;
}

#datalink {
  font-size:.5em;
  color:#317eac;
  padding-left:5px;
}

#headnote {
  font-size:.6em;
  color:#787878;
}

#note {
  font-size:.8em;
  color:#787878;
}

#headpoints {
 font-size:12pt;
 color: #585858; 
 padding-left: 15px;
}
#rcorners2 {
    border-radius: 25px;
    border: 2px solid #73AD21;
    padding: 20px; 
    width: auto;
    height: auto;    
}

#rcorners3 {
    border-radius: 25px;
    border: 2px solid #317eac;
    padding: 20px; 
    width: auto;
    height: auto;    
}
 </style>

 

 

 